startDelaySeconds: 0
jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:1234/jmxrmi
ssl: false
lowercaseOutputName: true
lowercaseOutputLabelNames: true
whitelistObjectNames:
  - kafka.connect:type=connect-worker-metrics
  - kafka.connect:type=connect-metrics,client-id=*
  - kafka.connect:type=connector-task-metrics,connector=*,task=*
blacklistObjectNames:
  - org.apache.cassandra.metrics:type=ColumnFamily,*
rules:
  - pattern: ".*"