{
 "title": "MongoDB Kafka Connect Dashboard",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "Kafka connect CPU Usage",
   "type": "timeseries",
   "description": "The recent cpu usage for the whole system",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "java_lang_operatingsystem_systemcpuload{app=\"cp-kafka-connect\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Kafka Connect Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{app=\"cp-kafka-connect\"}",
     "legendFormat": "{{instance}}-Heap"
    },
    {
     "expr": "java_lang_memory_nonheapmemoryusage_used{app=\"cp-kafka-connect\"}",
     "legendFormat": "{{instance}}-NoHeap"
    }
   ]
  },
  {
   "title": "Poll durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(com_mongodb_kafka_connect_source_task_metrics_in_task_poll_duration_ms{}[2m])",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "Change Stream Lag",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "com_mongodb_kafka_connect_source_task_metrics_latest_mongodb_time_difference_secs{task=~\".+change-stream.+\"}",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "framework durations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(com_mongodb_kafka_connect_source_task_metrics_in_connect_framework_duration_ms{}[2m])",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "records in per seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "rate(com_mongodb_kafka_connect_source_task_metrics_records{}[2m])",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "failed records",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "increase(com_mongodb_kafka_connect_source_task_metrics_records[2m]) - increase(com_mongodb_kafka_connect_source_task_metrics_records_filtered[2m]) - increase(com_mongodb_kafka_connect_source_task_metrics_records_acknowledged[2m])",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "bytes read in per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(com_mongodb_kafka_connect_source_task_metrics_mongodb_bytes_read{}[2m])",
     "legendFormat": "{{task}}"
    }
   ]
  },
  {
   "title": "average message size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(com_mongodb_kafka_connect_source_task_metrics_mongodb_bytes_read{}[2m]) / rate(com_mongodb_kafka_connect_source_task_metrics_records{}[2m])",
     "legendFormat": "{{task}}"
    },
    { "legendFormat": "{{task}}" }
   ]
  }
 ]
}